/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingsRouteImport } from './routes/writings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PerformancesRouteImport } from './routes/performances'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PerformancesIndexRouteImport } from './routes/performances.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PerformancesSlugRouteImport } from './routes/performances.$slug'

const WritingsRoute = WritingsRouteImport.update({
  id: '/writings',
  path: '/writings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformancesRoute = PerformancesRouteImport.update({
  id: '/performances',
  path: '/performances',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const PerformancesIndexRoute = PerformancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PerformancesRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const PerformancesSlugRoute = PerformancesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PerformancesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/performances': typeof PerformancesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writings': typeof WritingsRoute
  '/performances/$slug': typeof PerformancesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/performances/': typeof PerformancesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writings': typeof WritingsRoute
  '/performances/$slug': typeof PerformancesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/performances': typeof PerformancesIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/performances': typeof PerformancesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writings': typeof WritingsRoute
  '/performances/$slug': typeof PerformancesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/performances/': typeof PerformancesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/performances'
    | '/projects'
    | '/research'
    | '/sitemap.xml'
    | '/writings'
    | '/performances/$slug'
    | '/projects/$slug'
    | '/performances/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/research'
    | '/sitemap.xml'
    | '/writings'
    | '/performances/$slug'
    | '/projects/$slug'
    | '/performances'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/performances'
    | '/projects'
    | '/research'
    | '/sitemap.xml'
    | '/writings'
    | '/performances/$slug'
    | '/projects/$slug'
    | '/performances/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PerformancesRoute: typeof PerformancesRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResearchRoute: typeof ResearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WritingsRoute: typeof WritingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writings': {
      id: '/writings'
      path: '/writings'
      fullPath: '/writings'
      preLoaderRoute: typeof WritingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performances': {
      id: '/performances'
      path: '/performances'
      fullPath: '/performances'
      preLoaderRoute: typeof PerformancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/performances/': {
      id: '/performances/'
      path: '/'
      fullPath: '/performances/'
      preLoaderRoute: typeof PerformancesIndexRouteImport
      parentRoute: typeof PerformancesRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/performances/$slug': {
      id: '/performances/$slug'
      path: '/$slug'
      fullPath: '/performances/$slug'
      preLoaderRoute: typeof PerformancesSlugRouteImport
      parentRoute: typeof PerformancesRoute
    }
  }
}

interface PerformancesRouteChildren {
  PerformancesSlugRoute: typeof PerformancesSlugRoute
  PerformancesIndexRoute: typeof PerformancesIndexRoute
}

const PerformancesRouteChildren: PerformancesRouteChildren = {
  PerformancesSlugRoute: PerformancesSlugRoute,
  PerformancesIndexRoute: PerformancesIndexRoute,
}

const PerformancesRouteWithChildren = PerformancesRoute._addFileChildren(
  PerformancesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PerformancesRoute: PerformancesRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResearchRoute: ResearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WritingsRoute: WritingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
